<?php

/**
 * @file
 * Integrates the DPS PX Pay gateway with Drupal Commerce.
 */

define('COMMERCE_DPS_PXPAY_USERID', 'Sample User');
define('COMMERCE_DPS_PXPAY_KEY', 'Sample Key');
define('COMMERCE_DPS_PXPAY_SERVER', 'https://sec.paymentexpress.com/pxpay/pxaccess.aspx');
define('COMMERCE_DPS_PXPAY_CURRENCY', 'NZD');
define('COMMERCE_DPS_PXPAY_CANCEL_RETURN_URL', 'cart');
define('COMMERCE_DPS_PXPAY_REFPREFIX', 'Website Order');

/**
 * Implements hook_menu().
 */
function commerce_dps_pxpay_menu() {
  // Define an always-accessible path to receive FPRN (Fail-proof
  // Result Notification).
  $items['checkout/%commerce_order/dps_pxpay_fprn'] = array(
    'page callback' => 'commerce_dps_pxpay_process_fprn',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_commerce_payment_method_info().
 */
function commerce_dps_pxpay_commerce_payment_method_info() {
  $payment_methods = array();
  $payment_methods['commerce_dps_pxpay'] = array(
    // Translatable full title of the payment method, used in
    // administrative interfaces.
    'title' => t('DPS Payment Express PX Pay'),
    // Abbreviated title that may simply include the payment
    // provider’s name as it makes sense to the customer (i.e. you
    // would display PayPal, not PayPal WPS to a customer); defaults
    // to the title.
    'short_title' => t('Payment Express'),
    // Title to display on forms where the payment method is selected
    // and may include HTML for methods that require images and
    // special descriptions; defaults to the title.
    'display_title' => t('Credit card'),
    // Translatable description of the payment method, including the
    // nature of the payment and the payment gateway that actually
    // captures the payment.
    'description' => t('Provides integration with the DPS Payment Express PX Pay payment gateway.'),
    // Whether the default payment method rule configuration for this
    // payment method should be enabled by default.
    'active' => FALSE,
    // Whether payments can be processed via this payment method
    // through the administrative payment terminal on an order’s
    // Payment tab.
    'terminal' => FALSE,
    // Whether the customer must be redirected offsite to put in their
    // payment information; used specifically by the Off-site payment
    // redirect checkout pane.
    'offsite' => TRUE,
    // Whether to automatically redirect the user offsite.
    'offsite_autoredirect' => TRUE,
    // Returns elements that should be submitted to the redirected
    // payment service; because of the array merge that happens upon
    // return, the service’s URL that should receive the POST
    // variables should be set in the #action property of the returned
    // form array
    'redirect_form' => 'commerce_dps_pxpay_redirect_form',
    // Callbacks are automatically set using default method format,
    // see URL in function comment for details.
    //
    // Card on File callbacks.
    'cardonfile' => array(
      'charge callback' => 'commerce_dps_pxpay_cardonfile_charge',
      'update callback' => 'commerce_dps_pxpay_cardonfile_update',
      'delete callback' => 'commerce_dps_pxpay_cardonfile_delete',
    ),
  );
  return $payment_methods;
}

/**
 * Implements hook_form_FORM_ID_alter() for
 * 'commerce_checkout_form_review'.
 */
function commerce_dps_pxpay_form_commerce_checkout_form_review_alter(&$form, $form_state, $form_id) {
  array_unshift($form['buttons']['continue']['#submit'], 'commerce_dps_pxpay_form_commerce_checkout_form_review_continue_button_submit');
}

/**
 * Injected submit callback for Order Review form's Continue button.
 *
 * When commerce_dps_pxpay_redirect_form is generating order redirect
 * form, form values submitted from the review screen (??) are not
 * available. If the user selected an existing card we need to fire
 * the transaction and skip redirect.
 *
 * Storing in the order feels wrong since we might be seeing a second
 * transaction attempt on the same order, would be nice to clean this
 * up a bit.
 *
 * @see https://www.drupal.org/node/2410503
 *
 */
function commerce_dps_pxpay_form_commerce_checkout_form_review_continue_button_submit(&$form, &$form_state) {
  // Obtain payment method and instance.
  list($payment_method, $rule_name) = explode('|', $form_state['values']['commerce_payment']['payment_method']);

  if ($payment_method == 'commerce_dps_pxpay') {
    // Check a submitted cardonfile value; confirms payment
    // processor selected is CoF enabled etc.
    if (isset($form_state['values']['commerce_payment']['payment_details']['cardonfile'])) {
      $selected_card = $form_state['values']['commerce_payment']['payment_details']['cardonfile'];
      if ($selected_card != 'new') {
        // Check we have $order in the expected location.
        if (isset($form_state['build_info']['args'][0]->type) && $form_state['build_info']['args'][0]->type == 'commerce_order') {
          // Obtain order details.
          $order = $form_state['build_info']['args'][0];
          $wrapper = entity_metadata_wrapper('commerce_order', $order);
          $charge = commerce_line_items_total($wrapper->commerce_line_items);
          // Set up transaction to process.
          $transaction = commerce_payment_transaction_new($payment_method, $order->order_id);
          $transaction->amount = $charge['amount'];
          $transaction->currency_code = $charge['currency_code'];
          $transaction->status = COMMERCE_PAYMENT_STATUS_PENDING;
          $transaction->instance_id = $form_state['values']['commerce_payment']['payment_method'];
          $transaction->data['cardonfile_selected'] =
            $form_state['values']['commerce_payment']['payment_details']['cardonfile'];
          $transaction->data['debug'] = __FILE__ . '@' . (__LINE__ + 1);
          commerce_payment_transaction_save($transaction);
          // Record pending transaction against order.
          $order->data['commerce_dps_pxpay']['cardonfile_transaction'] = $transaction;
          commerce_order_save($order);
        }
      }
    }
  }
}

/**
 * Drupal Commerce redirect_form callback.
 */
function commerce_dps_pxpay_redirect_form($form, &$form_state, $order, $payment_method) {
  // Return error if DPS payment gateway userid and key unconfigured.
  if (empty($payment_method['settings']['commerce_dps_pxpay_userid']) ||
    empty($payment_method['settings']['commerce_dps_pxpay_key'])
  ) {
    drupal_set_message(t('The DPS payment gateway cannot be used at this time'), 'error');
    watchdog('commerce_dps_pxpay', 'Unable to generate form for PX Pay payment gateway as the User ID and Key are not configured.', array(), WATCHDOG_ERROR);
    return array();
  }

  // If Card on File enabled, configured and selected, use that to
  // shortcut the redirect checkout.
  if (module_exists('commerce_cardonfile') && isset($payment_method['settings']['cardonfile']) && $payment_method['settings']['cardonfile']) {
    if (isset($order->data['commerce_dps_pxpay']['cardonfile_transaction']->data['cardonfile_selected'])) {
      $card_data = commerce_cardonfile_load($order->data['commerce_dps_pxpay']['cardonfile_transaction']->data['cardonfile_selected']);
      $wrapper = entity_metadata_wrapper('commerce_order', $order);
      $charge = commerce_line_items_total($wrapper->commerce_line_items);
      if (commerce_dps_pxpay_cardonfile_charge($payment_method, $card_data, $order)) {
        commerce_payment_redirect_pane_next_page($order);
        drupal_goto(commerce_checkout_order_uri($order));
      }
      else {
        drupal_set_message('Unable to process transaction via stored card, redirecting to DPS for payment.', 'error');
        watchdog('commerce_dps_pxpay', 'Attempt at billing via PX Post Token Billing failed.', array(), WATCHDOG_NOTICE);
      }
    }
  }

  $settings = array(
    // Return to the previous page when payment is cancelled.
    'cancel_return' => url('checkout/' . $order->order_id . '/payment/back/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
    // Return to the payment redirect page for processing successful payments.
    'return' => url('checkout/' . $order->order_id . '/dps_pxpay_fprn/' . $order->data['payment_redirect_key'], array('absolute' => TRUE)),
    // Specify the current payment method instance ID in the notify_url.
    'payment_method' => $payment_method['instance_id'],
  );

  return commerce_dps_pxpay_order_form($form, $form_state, $order, $payment_method['settings'] + $settings);
}

/**
 * Payment method callback: settings form.
 */
function commerce_dps_pxpay_settings_form($settings = NULL) {
  module_load_include('inc', 'commerce_dps_pxpay', 'commerce_dps');
  module_load_include('inc', 'commerce_dps_pxpay', 'commerce_dps_pxpay');
  $form = array();

  $settings = (array) $settings + array(
      'commerce_dps_pxpay_userid' => COMMERCE_DPS_PXPAY_USERID,
      'commerce_dps_pxpay_key' => COMMERCE_DPS_PXPAY_KEY,
      'commerce_dps_pxpay_server' => COMMERCE_DPS_PXPAY_SERVER,
      'commerce_dps_pxpay_currency' => COMMERCE_DPS_PXPAY_CURRENCY,
      'commerce_dps_pxpay_cancel_return_url' => COMMERCE_DPS_PXPAY_CANCEL_RETURN_URL,
      'commerce_dps_pxpay_refprefix' => COMMERCE_DPS_PXPAY_REFPREFIX,
      'commerce_dps_pxpay_log_transactions' => 0,
      'cardonfile' => FALSE,
      'continuous' => FALSE,
      'pxpost_username' => '',
      'pxpost_password' => '',
    );

  $form['commerce_dps_pxpay_userid'] = array(
    '#type' => 'textfield',
    '#title' => t('PX Pay User Id'),
    '#description' => t('PX Pay User Id that was issued by Payment Express.'),
    '#default_value' => $settings['commerce_dps_pxpay_userid'],
    '#required' => TRUE,
  );

  $form['commerce_dps_pxpay_key'] = array(
    '#type' => 'textfield',
    '#title' => t('PX Pay key'),
    '#description' => t('PX Pay Key that was issued by Payment Express.'),
    '#default_value' => $settings['commerce_dps_pxpay_key'],
    '#required' => TRUE,
  );

  //
  $form['commerce_dps_pxpay_server'] = array(
    '#type' => 'select',
    '#title' => t('PX Pay server'),
    '#description' => t('If you are using the DPS PXPay 2.0 service, select it here.'),
    '#options' => array(
      'https://sec.paymentexpress.com/pxpay/pxaccess.aspx' => ('PX Pay'),
      'https://sec.paymentexpress.com/pxaccess/pxpay.aspx' => ('PX Pay 2.0'),
    ),
    '#default_value' => $settings['commerce_dps_pxpay_server'],
    '#required' => TRUE,
  );

  $form['commerce_dps_pxpay_currency'] = array(
    '#type' => 'select',
    '#title' => t('Currency code'),
    '#description' => t('Transactions can only be processed in one of the listed currencies.'),
    '#options' => commerce_dps_currencies(),
    '#default_value' => $settings['commerce_dps_pxpay_currency'],
  );

  $form['commerce_dps_pxpay_cancel_return_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Cancel return URL'),
    '#description' => t('Specify the path customers who cancel their DPS PX Pay payment will be directed to when they return to your site.'),
    '#default_value' => $settings['commerce_dps_pxpay_cancel_return_url'],
    '#size' => 32,
    '#field_prefix' => url(NULL, array('absolute' => TRUE)) . (variable_get('clean_url', 0) ? '' : '?q='),
  );

  // A hook is available to modify this in transit if you need
  // something more complicated; see
  // https://www.drupal.org/node/1848344
  $form['commerce_dps_pxpay_refprefix'] = array(
    '#type' => 'textfield',
    '#title' => t('Merchant Reference Prefix'),
    '#description' => t('Prefix to order number reference at DPS, eg "Website Order #1234."'),
    '#default_value' => $settings['commerce_dps_pxpay_refprefix'],
    '#required' => TRUE,
  );

  // Card On File support requires the Card on File module.
  if (module_exists('commerce_cardonfile')) {
    $form['cardonfile'] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable Card on File functionality with this payment method.'),
      '#description' => t('Ensure token billing is enabled on your Payment Express account, and supply PX Post credentials below.'),
      '#default_value' => $settings['cardonfile'],
    );

    $form['pxpost_username'] = array(
      '#type' => 'textfield',
      '#title' => t('PX Post Username'),
      '#default_value' => $settings['pxpost_username'],
      '#states' => array(
        'visible' => array(
          ':input[name="parameter[payment_method][settings][payment_method][settings][cardonfile]"]' => array('checked' => TRUE),
        ),
      ),
    );

    $form['pxpost_password'] = array(
      '#type' => 'password',
      '#title' => t('PX Post Password'),
      '#default_value' => $settings['pxpost_password'],
      '#states' => array(
        'visible' => array(
          ':input[name="parameter[payment_method][settings][payment_method][settings][cardonfile]"]' => array('checked' => TRUE),
        ),
      ),
    );
  }
  else {
    $form['cardonfile'] = array(
      '#type' => 'markup',
      '#markup' => t('To enable Card on File functionality download and install the Card on File module.'),
    );
  }

  $form['commerce_dps_pxpay_log_transactions'] = array(
    '#type' => 'select',
    '#title' => t('Record transaction information to Drupal logs.'),
    '#description' => t('Record communication with DPS server to Drupal logs. For development only.'),
    '#options' => array(
      0 => ('Disabled (production)'),
      1 => ('Enabled (development)'),
    ),
    '#default_value' => $settings['commerce_dps_pxpay_log_transactions'],
    '#required' => TRUE,
  );

  return $form;
}

/**
 * Payment method callback: checkout form.
 */
function commerce_dps_pxpay_submit_form($payment_method, $pane_values, $checkout_pane, $order) {
  $pxlogo_args = array(
    'path' => drupal_get_path('module', 'commerce_dps_pxpay') . '/images/dps_paymentexpress_small.png',
    'alt' => t('DPS - Payment Gateway by Payment Express.'),
    'title' => t('DPS - Payment Gateway by Payment Express.'),
    'attributes' => array(
      'class' => 'commerce-dps-pxpay-logo',
    ),
  );
  $pxlink_args = array(
    'html' => TRUE,
    'attributes' => array('target' => '_blank'),
  );
  $pxlogo = theme('image', $pxlogo_args);
  $form['commerce_dps_pxpay_logo']
    = array('#markup' => l($pxlogo, 'http://www.paymentexpress.com', $pxlink_args));

  return $form;
}

/**
 * Called from commerce_dps_pxpay_redirect_form().
 */
function commerce_dps_pxpay_order_form($form, &$form_state, $order, $settings) {
  module_load_include('inc', 'commerce_dps_pxpay', 'commerce_dps');
  module_load_include('inc', 'commerce_dps_pxpay', 'commerce_dps_pxpay');

  $cardonfile_capable = module_exists('commerce_cardonfile') && !empty($settings['cardonfile']);

  $wrapper = entity_metadata_wrapper('commerce_order', $order);

  $amount = $wrapper->commerce_order_total->amount->value();
  $currency_code = $wrapper->commerce_order_total->currency_code->value();
  $amount = commerce_currency_amount_to_decimal($amount, $currency_code);
  $amount = commerce_dps_format_amount($amount, $currency_code);
  $cardonfile = isset($settings['cardonfile']) ? $settings['cardonfile'] : FALSE;

  $transaction = array(
    'user_id' => $settings['commerce_dps_pxpay_userid'],
    'server' => $settings['commerce_dps_pxpay_server'],
    'key' => $settings['commerce_dps_pxpay_key'],
    'amount' => $amount,
    'type' => 'Purchase',
    'txn_id' => substr(uniqid($order->order_number . '-'), 0, 16),
    'reference' => $settings['commerce_dps_pxpay_refprefix'] . " #" . $order->order_number,
    'currency' => isset($currency_code) ? $currency_code : $settings['commerce_dps_pxpay_currency'],
    'url_success' => $settings['return'],
    'url_failure' => $settings['cancel_return'],
    'email' => $order->mail,
    'log' => $settings['commerce_dps_pxpay_log_transactions'],
    'add_bill_card' => $cardonfile,
  );

  // Allow modules to alter parameters of the API request.
  drupal_alter('commerce_dps_pxpay_transaction_data', $transaction, $order, $settings);

  if ($url = commerce_dps_pxpay_generate_request($transaction)) {
    // Compose a non-FAPI button which submits offsite.
    $parts = parse_url($url);
    $form['#action'] = $parts['scheme'] . '://' . $parts['host'] . $parts['path'];
    $form['#method'] = 'get';
    // PxPay 1 includes data in the query, PxPay 2 does not.
    if (isset($parts['query'])) {
      parse_str($parts['query'], $data);
      foreach ($data as $name => $value) {
        $form[$name] = array(
          '#type' => 'hidden',
          '#value' => $value,
        );
      }
    }
    $form['submit'] = array(
      '#type' => 'submit',
      '#value' => t('Proceed to DPS'),
    );
    return $form;
  }
  else {
    watchdog('commerce_dps_pxpay', 'Unable to generate DPS request with settings: @settings', array('@settings' => print_r($settings, 1)), WATCHDOG_DEBUG);
  }
}

/**
 * Processes an normal payment or FPRN.
 *
 * @return void
 */
function commerce_dps_pxpay_process_fprn($order) {
  // Exclude "PXL1" (DPS FPRN) from creating user accounts.
  /*
    $user_email_verification = variable_get('user_email_verification');
    watchdog('commerce_dps_pxpay', $_SERVER['HTTP_USER_AGENT']);
    if (isset($_SERVER['HTTP_USER_AGENT']) && $_SERVER['HTTP_USER_AGENT'] == 'PXL1') {
      if ($user_email_verification) {
        variable_set('user_email_verification', TRUE);
      }
    }
  */
  module_load_include('inc', 'commerce_dps_pxpay', 'commerce_dps');
  module_load_include('inc', 'commerce_dps_pxpay', 'commerce_dps_pxpay');

  if (!$order) {
    return drupal_not_found();
  }

  $payment_method = $order->data['payment_method'];
  $payment_data = commerce_payment_method_instance_load($payment_method);

  $transaction = array(
    'server' => COMMERCE_DPS_PXPAY_SERVER,
    'user_id' => $payment_data['settings']['commerce_dps_pxpay_userid'],
    'key' => $payment_data['settings']['commerce_dps_pxpay_key'],
    'log' => $payment_data['settings']['commerce_dps_pxpay_log_transactions'],
  );

  // Make sure result is set from DPS
  if (isset($_GET['result'])) {
    $transaction['result'] = $_GET['result'];
  }
  else {
    watchdog('commerce_dps_pxpay', 'Transaction result data not found.', array(), WATCHDOG_ERROR);
    if (preg_match('/(\?|\&)result=/', $_SERVER['REQUEST_URI'])) {

      watchdog(
        'commerce_dps_pxpay',
        'Please see !link for how to configure your webserver to accept DPS return requests.',
        array('!link' => l('drupal.org #1799294', 'https://drupal.org/node/1799294')),
        WATCHDOG_WARNING
      );

      drupal_set_message('Server configuration prevented DPS transaction completion. Please advise site administrator to check Drupal logs for details.', 'error');
    }
    drupal_goto($payment_data['settings']['commerce_dps_pxpay_cancel_return_url']);
  }

  // Get DPS payment information
  $response = commerce_dps_pxpay_process_response($transaction);
  // Proccess the order payment. This calls drupal_goto() so will die.
  commerce_dps_pxpay_fprn_process($order, $response, $payment_data['settings']);
}

/**
 * Payment method callback: process an payment once it's been validated.
 *
 * @param  object $order The order object being processed
 * @param  array $payment Payment details from DPS
 * @param  string $settings User defined settings
 *
 * @return void
 */
function commerce_dps_pxpay_fprn_process($order, &$payment, $settings) {
  // Do not perform any processing on transactions here that do not
  // have a transaction ID.
  if (empty($payment['TxnId'])) {
    drupal_goto($settings['commerce_dps_pxpay_cancel_return_url']);
  }

  // Exit when we don't get a payment status we recognize.
  if (!$payment['Success']) {
    // Only add the transaction if we do not have the TxnId stored.
    $remote_ids = commerce_dps_pxpay_get_remote_ids($order->order_id);
    if (!in_array($payment['TxnId'], $remote_ids)) {
      // Write transaction information if payment failed.
      commerce_dps_pxpay_order_transaction($order, $payment, COMMERCE_PAYMENT_STATUS_FAILURE);
      watchdog('commerce_dps_pxpay', 'DPS PX Pay transaction failed validation. Cart order ID: @cart_order', array('@cart_order' => $order->order_number), WATCHDOG_NOTICE);
      drupal_set_message(t('The transaction failed validation. Please contact us for assistance. Reference Order Id: @orderid', array('@orderid' => $order->order_number)));
    }
    drupal_goto($settings['commerce_dps_pxpay_cancel_return_url']);
  }

  // Local validation.
  $merchant_reference = $settings['commerce_dps_pxpay_refprefix'] . " #" . $order->order_number;

  // Special case: If $order->mail is "some+verpstring@example.com",
  // DPS will return "some verpstring@example.com". Perhaps we should
  // be urlencoding email address for DPS? Anyway, for now we test
  // both because otherwise orders using VERP addresses would fail.
  $order_mail = str_replace('+', ' ', $order->mail);
  $payment_mail = $payment['EmailAddress'];

  if ($merchant_reference != $payment['MerchantReference'] || ($order->mail != $payment_mail && $order_mail != $payment_mail)) {
    watchdog('commerce_dps_pxpay', 'DPS PX Pay details do not match order details! Cart order ID: @cart_order', array('@cart_order' => $order->order_number), WATCHDOG_NOTICE);
    drupal_set_message(
      t('The details of your DPS PX Pay payment do not match your order. Please contact us for assistance. Reference Order Id: @orderid', array('@orderid' => $order->order_number))
    );
    // Write transaction information if payment details do not match order.
    commerce_dps_pxpay_order_transaction($order, $payment, COMMERCE_PAYMENT_STATUS_FAILURE);
    drupal_goto($settings['commerce_dps_pxpay_cancel_return_url']);
  }

  $remote_ids = commerce_dps_pxpay_get_remote_ids($order->order_id);

  // Only add the transaction if we do not have the TxnId stored.
  if (!in_array($payment['TxnId'], $remote_ids)) {
    watchdog('commerce_dps_pxpay', 'DPS PX Pay transaction succeeded. Cart order ID: @cart_order', array('@cart_order' => $order->order_number), WATCHDOG_NOTICE);
    drupal_set_message(t('Transaction succeeded. Reference Order Id: @orderid', array('@orderid' => $order->order_number)));
    // Include information about the payment method in use.
    $payment['method_settings'] = $settings;
    // Write transaction information when payment was successful.
    commerce_dps_pxpay_order_transaction($order, $payment, COMMERCE_PAYMENT_STATUS_SUCCESS);
  }
  // Save to completed orders in session so it's viewable. Here to let
  // user view order after FPRN has occurred.
  commerce_cart_order_session_save($order->order_id, TRUE);
  commerce_payment_redirect_pane_next_page($order);
  drupal_goto(commerce_checkout_order_uri($order));
}

/**
 * Card on file callback: charge the associated customer payment
 * profile using PX Post.
 *
 * @see https://www.drupal.org/node/2397663
 */
function commerce_dps_pxpay_cardonfile_charge($payment_method, $card_data, $order, $charge = NULL) {
  module_load_include('module', 'commerce_dps_pxpay', 'commerce_dps_pxpost');

  // Clean up temporary transaction(s) associated with Card on File.
  $transactions = commerce_payment_transaction_load_multiple(array(), array(
    'order_id' => $order->order_id,
    'payment_method' => 'commerce_dps_pxpay',
  ));
  foreach ($transactions as $transaction_id => $transaction) {
    // Check is probably redundant, since else we shouldn't be here.
    if ($transaction->instance_id == $payment_method['instance_id']) {
      if (isset($transaction->data['cardonfile_selected']) && $transaction->data['cardonfile_selected'] == $card_data->card_id) {
        commerce_payment_transaction_delete($transaction_id);
      }
    }
  }

  // Copy the PX Post details to set up the settings array, use PX
  // Post charge callback.
  if (!empty($payment_method['settings']['pxpost_username']) &&
    !empty($payment_method['settings']['pxpost_username'])
  ) {
    $payment_method['settings'] += array(
      'username' => $payment_method['settings']['pxpost_username'],
      'password' => $payment_method['settings']['pxpost_password'],
      'reference_prefix' => $payment_method['settings']['commerce_dps_pxpay_refprefix'],
      'log_transactions' => $payment_method['settings']['commerce_dps_pxpay_log_transactions'],
      'server' => COMMERCE_DPS_PXPOST_SERVER,
    );
    return commerce_dps_pxpost_cardonfile_charge($payment_method, $card_data, $order);
  }
}

/**
 * Card on file callback: deletes the associated customer payment profile.
 *
 * AFAIK PX doesn't offer a means to update the billing ID remotely,
 * so we just return TRUE to give commerce_cardonfile OK to delete
 * the card data locally.
 */
function commerce_dps_pxpay_cardonfile_update($form, &$form_state, $payment_method, $card_data) {
  return TRUE;
}

/**
 * Card on file callback: deletes the associated customer payment
 * profile.
 *
 * AFAIK PX doesn't offer a means to delete the billing ID remotely,
 * so we just return TRUE to give commerce_cardonfile OK to delete
 * the card data locally.
 */
function commerce_dps_pxpay_cardonfile_delete($form, &$form_state, $payment_method, $card_data) {
  return TRUE;
}
