<?php

/**
 *
 */

/**
 * Returns an array of possible currency codes.
 */
function commerce_dps_currencies() {
  return array(
    'AUD' => 'Australian Dollar',
    'CAD' => 'Canadian Dollar',
    'EUR' => 'Euro',
    'FJD' => 'Fiji Dollar',
    'FRF' => 'French Franc',
    'HKD' => 'Hong Kong Dollar',
    'JPY' => 'Japanese Yen',
    'KWD' => 'Kuwaiti Dinar',
    'MYR' => 'Malaysian Ringgit',
    'NZD' => 'New Zealand Dollar',
    'PNG' => 'Papua New Guinea Kina',
    'ZAR' => 'South African Rand',
    'SGD' => 'Singapore Dollar',
    'SBD' => 'Solomon Islands Dollar',
    'TOP' => 'Tongan Pa\'anga',
    'WST' => 'Samoan Tala',
    'CHF' => 'Swiss Franc',
    'GBP' => 'United Kingdom Pound',
    'USD' => 'United States Dollar',
    'VUV' => 'Vanuatu Vatu',
  );
}
