commerce_payment.commerce_payment_gateway.plugin.dps_pxpost:
  type: commerce_payment_gateway_configuration
  mapping:
    px_user:
      type: string
      label: 'PxPost Username'
    px_key:
      type: string
      label: 'PxPost Password'
    px_ref_prefix:
      type: string
      label: 'Merchant Reference Prefix'
